---
- name: Network Getting Started First Playbook Extended
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all 
  tasks: 
    
    - name: Get config for VyOS devices
      ios_facts:
        gather_subset: all

    - name: Display the device details
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

    - name: Show running-config
      ios_config:
        backup: yes
        lines:
          - do show version
      register: running_config_output
    
    - name: Inspect
      debug:
        var: running_config_output


    - name: Display running-config output
      debug:
        msg: "{{ running_config_output }}"
